version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: matheus_database
      POSTGRES_USER: user_matheus_fullstack
      POSTGRES_PASSWORD: Evssalvo9185
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
